/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import Entity.Warehouse;
import java.awt.Component;
import java.awt.Container;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Bernardo
 */
public class EditWrhForm extends javax.swing.JFrame {

    Warehouse wrh;
    /**
     * Creates new form EditWrhForm
     */
    public EditWrhForm() {
        initComponents();
    }

    public EditWrhForm(Warehouse wrh) {
        initComponents();
        this.wrh = wrh;
        wrhNameTxt.setText(wrh.getWarehouseName());
        String maxString = Integer.toString(wrh.getMaxProduct());
        wrhMaxTxt.setText(maxString);
        String minString = Integer.toString(wrh.getMinProduct());
        wrhMinTxt.setText(minString);       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrhNameTxt = new javax.swing.JTextField();
        wrhMinTxt = new javax.swing.JTextField();
        wrhMaxTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        updateWrhBtn = new javax.swing.JButton();
        cancelWrhEditBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Min: ");

        jLabel3.setText("Max: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Edit Warehouse");

        updateWrhBtn.setText("Update");
        updateWrhBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWrhBtnActionPerformed(evt);
            }
        });

        cancelWrhEditBtn.setText("Cancel");
        cancelWrhEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelWrhEditBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cancelWrhEditBtn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wrhNameTxt)
                            .addComponent(wrhMaxTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(wrhMinTxt))))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(updateWrhBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrhNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrhMinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrhMaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateWrhBtn)
                    .addComponent(cancelWrhEditBtn))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelWrhEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelWrhEditBtnActionPerformed
        closeUpdateWarehouse();
    }//GEN-LAST:event_cancelWrhEditBtnActionPerformed

    private void updateWrhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateWrhBtnActionPerformed
        try {
            if (allTextFilled(this.getContentPane())) {
                Warehouse warehouse = new Warehouse();

                warehouse.setWarehouseName(wrhNameTxt.getText());
                int min = Integer.parseInt(wrhMinTxt.getText());
                warehouse.setMinProduct(min);
                int max = Integer.parseInt(wrhMaxTxt.getText());
                warehouse.setMaxProduct(max);
                updateWarehouse(warehouse, this.wrh.getWarehouseId());
            } else {
                JOptionPane.showMessageDialog(null, "All inputs must be filled");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Inputs ID, Min and Max "
                    + "should be numbers");
        }

    }//GEN-LAST:event_updateWrhBtnActionPerformed

    private void updateWarehouse(Warehouse warehouse, int id) {
        //TODO Validar todos los campos llenos
        
        try {
            ConDB conn = new ConDB();
            String query = "UPDATE warehouses SET warehouseName = ?,"
                    + "minProduct = ?, maxProduct = ? WHERE id = " + id;
            
            PreparedStatement pst = conn.getConnection().prepareStatement(query);
            pst.setString(1, warehouse.getWarehouseName());
            pst.setInt(2, warehouse.getMinProduct());
            pst.setInt(3, warehouse.getMaxProduct());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Warehouse updated");
            closeUpdateWarehouse();
        } catch (SQLException ex) {
            System.out.println(ex.getLocalizedMessage());
        }
    }
    
    public boolean allTextFilled(Container container) {
        for (Component component : container.getComponents()) {
            if (component instanceof JTextField) {
                //assert (((JTextField) component).getText().equals(""));
                if(((JTextField) component).getText().trim().isEmpty()) return false;
            }
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditWrhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditWrhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditWrhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditWrhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditWrhForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelWrhEditBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton updateWrhBtn;
    private javax.swing.JTextField wrhMaxTxt;
    private javax.swing.JTextField wrhMinTxt;
    private javax.swing.JTextField wrhNameTxt;
    // End of variables declaration//GEN-END:variables

    void closeUpdateWarehouse() {
        Inventory inventory = new Inventory();
        inventory.setVisible(true);
        this.dispose();
    }
}
